// Code generated by Kitex v0.3.0. DO NOT EDIT.

package itemservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"item_info/kitex_gen/item"
)

func serviceInfo() *kitex.ServiceInfo {
	return itemServiceServiceInfo
}

var itemServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ItemService"
	handlerType := (*item.ItemService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetItem":    kitex.NewMethodInfo(getItemHandler, newItemServiceGetItemArgs, newItemServiceGetItemResult, false),
		"UpdateItem": kitex.NewMethodInfo(updateItemHandler, newItemServiceUpdateItemArgs, newItemServiceUpdateItemResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "item",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.0",
		Extra:           extra,
	}
	return svcInfo
}

func getItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*item.ItemServiceGetItemArgs)
	realResult := result.(*item.ItemServiceGetItemResult)
	success, err := handler.(item.ItemService).GetItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceGetItemArgs() interface{} {
	return item.NewItemServiceGetItemArgs()
}

func newItemServiceGetItemResult() interface{} {
	return item.NewItemServiceGetItemResult()
}

func updateItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*item.ItemServiceUpdateItemArgs)
	realResult := result.(*item.ItemServiceUpdateItemResult)
	success, err := handler.(item.ItemService).UpdateItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceUpdateItemArgs() interface{} {
	return item.NewItemServiceUpdateItemArgs()
}

func newItemServiceUpdateItemResult() interface{} {
	return item.NewItemServiceUpdateItemResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetItem(ctx context.Context, req *item.GetItemRequest) (r *item.GetItemResponse, err error) {
	var _args item.ItemServiceGetItemArgs
	_args.Req = req
	var _result item.ItemServiceGetItemResult
	if err = p.c.Call(ctx, "GetItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateItem(ctx context.Context, req *item.UpdateItemRequest) (r *item.UpdateItemResponse, err error) {
	var _args item.ItemServiceUpdateItemArgs
	_args.Req = req
	var _result item.ItemServiceUpdateItemResult
	if err = p.c.Call(ctx, "UpdateItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
